### ISSUE TITLE
Does the wrapper still work with the 2017 Kraken API ?

### ISSUE THREAD

**Issue by Kinzowa** [leishman/kraken_ruby#21]
Hello, just to be sure before I start working on a trading bot.
Thanks !

**Comment by leishman** [comment]
I'm not sure. I haven't used it in a while. If you decide to test it, let me know!

**Comment by keo** [comment]
We're using it currently on Kraken. We've added a few things: https://github.com/debreczeni/kraken_ruby

**Comment by Kinzowa** [comment]
Thank you
